### ISSUE TITLE
Create the profile page

### ISSUE THREAD

**Issue by Aryan-219** [Aryan-219/LEGAL-BREEZE#3]

**Comment by AnushkJain2201** [comment]
I can do that. I am an expert in doing that, _I hope you know_.

**Comment by AnushkJain2201** [comment]
Share the design and assign me this issue, and I can see what I can do.

**Comment by Aryan-219** [comment]
Well, I already saw it coming :)
Looking forward to some cool stuff :)

**Comment by AnushkJain2201** [comment]
**You will not be disappointed, my lord !!**

**Comment by Aryan-219** [comment]
You can use the design of github profile. Similar to your story shop. 
No need to go for a brand new

**Comment by AnushkJain2201** [comment]
Okay

**Comment by Aryan-219** [comment]
Profile page created successfully
